### ISSUE TITLE
NewSongVoter

### ISSUE THREAD

**Issue by lthoedt** [lthoedt/MusicMan-API#11]
For bands,

- [ ] Each person can add songs to the voting list
- [ ] Each person can Vote between [-2, 2]
- [ ] List gets sorted by score
- [ ] Voting can be closed
